name: Codeowners - Legal

# **What it does**: 
# **Why we have it**:
# **Who does it impact**:

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - 'content/**'

jobs:
  codeowners-legal:
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.html_url }}

    steps:
      - name: Get files changed
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          # Base branch used to get changed files
          base: 'main'

          # Enables setting an output in the format in `${FILTER_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            rai:
              - 'content/**'
      
      - name: Check out repo
        if: ${{ steps.filter.outputs.rai}}
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Check content type
        id: checkContentType
        if: ${{ steps.filter.outputs.rai}}
        run: src/workflows/check-content-type.js
        env:
          FILE_PATHS_CONTENT_TYPES: ${{ steps.filter.outputs.rai_files }}
          CONTENT_TYPE: 'rai'

      - name: Add Legal team as a reviewer
        if: ${{ steps.checkContentType.outputs.contentType }}
        run: |
          has_reviewer=$(
            gh pr view $PR --json reviews |
            jq 'any(.reviews[]; select(length > 0))'
          )
          echo 'Reviewer: $has_reviewer'
          if ! $has_reviewer
          then
            echo "Adding rachmari as reviewer"
            gh pr edit $PR --add-reviewer rachmari
          fi
